version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: NOM_DevDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '4000:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
  fserv:
    image: python:3.9
    